# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcWdist_abs <- function(x, w) {
    .Call('_mgatk_calcWdist_abs', PACKAGE = 'mgatk', x, w)
}

calcWdist_euclidean <- function(x, w) {
    .Call('_mgatk_calcWdist_euclidean', PACKAGE = 'mgatk', x, w)
}

calcWdist_sqrt <- function(x, w) {
    .Call('_mgatk_calcWdist_sqrt', PACKAGE = 'mgatk', x, w)
}

#' Calculate a vector of gini indices from the rows of a matrix
#'
#' This function computes the row-wise Gini indices
#' sensitive to NAs
#'
#' @param x An m x n numeric matrix
#' @return A vector of length m with the Gini Index
#' computed for each row across all of the columns
#'
#' @examples
#'
#' x <- matrix(runif(1000), nrow = 20) # 50 samples
#' gi <- giniRows(x)
#'
#' @export
giniRows <- function(x) {
    .Call('_mgatk_giniRows', PACKAGE = 'mgatk', x)
}

#' Calculate a vector of gini indices from the rows of a matrix
#'
#' This function computes the column-wise Gini indices
#' sensitive to NAs
#'
#' @param x An m x n numeric matrix
#' @return A vector of length n with the Gini Index
#' computed for each column across all of the rows
#'
#' @examples
#'
#' x <- matrix(runif(1000), nrow = 20) # 50 samples
#' gi <- giniCols(x)
#'
#' @export
giniCols <- function(x) {
    .Call('_mgatk_giniCols', PACKAGE = 'mgatk', x)
}

#' Calculate the Gini Index using Rcpp
#'
#' Given a vector of numbers, calcuate the
#' Gini index being sensitive to NAs
#'
#' @param x A numeric vector
#' @return A float of the Gini index where values are
#' between [0,1]
#'
#' @examples
#'
#' x <- runif(1000)
#' gi <- giniCpp(x)
#'
#' @export
giniCpp <- function(x) {
    .Call('_mgatk_giniCpp', PACKAGE = 'mgatk', x)
}

