# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcWdist_euclidean <- function(x, w) {
    .Call('_mgatk_calcWdist_euclidean', PACKAGE = 'mgatk', x, w)
}

calcWdist_sqrt <- function(x, w) {
    .Call('_mgatk_calcWdist_sqrt', PACKAGE = 'mgatk', x, w)
}

